<?php

class Point3D extends Point2D
{
    public float $z;

    public function __construct(float $x, float $y, float $z)
    {
        parent::__construct($x, $y);
        $this->z = $z;
    }

    /**
     * @return float
     */
    public function getZ(): float
    {
        return $this->z;
    }

    /**
     * @param float $z
     */
    public function setZ(float $z): void
    {
        $this->z = $z;
    }

    public function setXYZ(float $x, float $y, float $z)
    {
        parent::setXY($x, $y); // TODO: Change the autogenerated stub
        $this->z = $z;
    }

    public function getXYZ()
    {
        return [parent::getX(), parent::getY(), $this->z];
    }

    public function toString()
    {
        return parent::toString() . $this->z; // TODO: Change the autogenerated stub
    }
}