<?php

use JetBrains\PhpStorm\Pure;

class MoveablePoint extends Point
{
    public float $xSpeed;
    public float $ySpeed;

    #[Pure] public function __construct(float $x, float $y, float $xSpeed, float $ySpeed)
    {
        parent::__construct($x, $y);
        $this->xSpeed = $xSpeed;
        $this->ySpeed = $ySpeed;
    }

    /**
     * @return float
     */
    public function getXSpeed(): float
    {
        return $this->xSpeed;
    }

    /**
     * @param float $xSpeed
     */
    public function setXSpeed(float $xSpeed): void
    {
        $this->xSpeed = $xSpeed;
    }

    /**
     * @return float
     */
    public function getYSpeed(): float
    {
        return $this->ySpeed;
    }

    /**
     * @param float $ySpeed
     */
    public function setYSpeed(float $ySpeed): void
    {
        $this->ySpeed = $ySpeed;
    }

    public function getSpeed()
    {
        return $speed = [$this->xSpeed, $this->ySpeed];
    }

    public function move()
    {
        echo parent::getX() + $this->xSpeed . "<br>";
        echo parent::getY() + $this->ySpeed . "<br>";
    }

    public function toString()
    {
        parent::toString(); // TODO: Change the autogenerated stub
        echo "xSpeed =  " . $this->xSpeed . "<br>";
        echo "ySpeed =  " . $this->ySpeed . "<br>";
    }
}